ja: update for 0.12.1
obsidianmd/obsidian-translations pull request #442
Opened 2021-04-27 10:54 UTC by yo-goto

- new string for 0.12.1 - all translated except for "Untitled"
- fixed some mistakes 
- updated ja.termbase.md(notation rules, term table)

2021-04-27 11:31 UTC, taksas requested changes
Untitledとインデキシング以外の部分についてです。

2021-04-27 11:31 UTC, taksas commented on ja.json
> +			"action-toggle-backlinks-in-document": "ドキュメント内バックリンクをトグル",
「トグル」と動詞として使うことは一般的にはあんまり無いように（私の体感ですが）思います。「ドキュメント内バックリンクを切り替え」でいいと思います。

2021-04-27 11:31 UTC, taksas commented on ja.json
> +			"desc": "コマンドを入力して機能を呼び出します。UIを使用したりショートカットを覚ることなくコマンドを使用できます。",
「ショートカットを覚ることなく」→「ショートカットを覚えることなく」だと思います。

2021-04-27 12:23 UTC, yo-goto commented on ja.json
> +			"action-toggle-backlinks-in-document": "ドキュメント内バックリンクをトグル",
｢toggle｣が結構やっかいというか、｢切り替え｣があまり当てはまらないものに対して迂回策的に使ってるんですよね。
あえて日本語にすると｢起動切り替え｣みたいになるので、いっそのこと｢切り替え｣がうまく当てはまらないなら横文字のトグルを使うかみたいな..
｢toggle pin｣ → ｢ピンをトグル｣
｢toggel spellcheck｣→スペルチェックをトグル
｢Toggle comments for selection｣→選択範囲のコメントをトグル
みたいな

2021-04-27 13:02 UTC, taksas commented on ja.json
> +			"action-toggle-backlinks-in-document": "ドキュメント内バックリンクをトグル",
なるほど、そういうことでしたか。
「～をトグル」でもいいと思います。

2021-04-27 13:41 UTC, yo-goto commented on ja.json
> +			"action-toggle-backlinks-in-document": "ドキュメント内バックリンクをトグル",
というか上の例であげたtoggleのやつ未訳でした、修正でまとめてコミットします。

2021-04-27 13:48 UTC, taksas approved these changes
大丈夫だと思います。

2021-04-27 13:48 UTC, yo-goto commented
レビューありがとうございました😊
Ready to be merged!

2021-04-28 05:36 UTC, taksas approved these changes

2021-04-28 06:49 UTC, ericaxu commented
Thanks so much for your collaboration on this!

2021-04-28 06:49 UTC, merged