Update Traditional Chinese translation
obsidianmd/obsidian-translations pull request #611
Opened 2022-04-20 11:48 UTC by SiderealArt

2022-04-20 12:46 UTC, pan93412 commented on zh-TW.json
> +			"option-text-font-description": "設置編輯或閱讀模式的字型。",
`設定`

2022-04-20 12:47 UTC, pan93412 commented on zh-TW.json
> +			"option-font-placeholder": "輸入字型名稱...",
3 dot 建議改成教育部規定的六點刪節號（⋯⋯／……）

2022-04-20 12:47 UTC, pan93412 commented on zh-TW.json
> +			"label-screenshot-unavailable": "螢幕截圖不可用",
「無螢幕截圖」應該會比較好。「螢幕截圖不可用」怪怪的。

2022-04-20 12:48 UTC, pan93412 commented on zh-TW.json
> +			"button-donate-to-unlimited": "向 Obsidian Unlimited 贊助",
「贊助 Obsidian Unlimited」會更簡潔。

2022-04-20 12:51 UTC, pan93412 commented on zh-TW.json
> +		"msg-sandbox-vault": "這是沙盒儲存庫。\n在此儲存庫做出的所有更動不會被儲存。",
`這是沙盒儲存庫。\n在此儲存庫做出的所有更動皆不儲存。` 應會更簡短

2022-04-20 12:51 UTC, pan93412 commented on zh-TW.json
> +			"mod-click-open-new-pane": "按下 {{key}} 後點一下在新窗格開啟",
原翻譯應該沒問題⋯⋯

2022-04-20 12:52 UTC, pan93412 commented on zh-TW.json
> +			"option-connect-obsidian-sync-description": "設置與現有遠端儲存庫同步的儲存庫。",
`設定`

2022-04-20 12:52 UTC, pan93412 commented on zh-TW.json
> +			"option-rename-vault": "重新命名儲存庫...",
刪節號問題，「……／⋯⋯」

2022-04-20 12:52 UTC, pan93412 commented on zh-TW.json
> +			"msg-error-nested": "無法將儲存庫移動到自己的子資料夾中。",
suggestion: `無法將儲存庫移至其子資料夾。`

2022-04-20 12:53 UTC, pan93412 commented on zh-TW.json
> +			"option-move-vault": "移動儲存庫...",
刪節號問題，「……／⋯⋯」

2022-04-20 12:53 UTC, pan93412 commented on zh-TW.json
> +			"msg-error-rename-open": "無法重新命名目前已開啟的儲存庫。",
`無法重新命名目前開啟的儲存庫。`

「已」可以省略

2022-04-20 12:54 UTC, pan93412 commented on zh-TW.json
> +			"placeholder-your-email": "您的電子郵件地址...",
刪節號問題，「……／⋯⋯」

2022-04-20 12:54 UTC, pan93412 commented on zh-TW.json
> +			"label-sandbox-vault-desc": "探索並試驗各種功能，您的更動不會被儲存。"
suggestion: `探索並試驗各種功能。不會儲存您的更動。`

2022-04-20 12:56 UTC, pan93412 commented on zh-TW.json
> +			"option-hide-title-description": "隱藏頁面標題。適用於您已在各個頁面的開頭設置自己的標題的情況。",
`隱藏頁面標題。適合您每個頁面有自己設定頁首的場景。`

2022-04-20 12:59 UTC, pan93412 commented
r? @emisjerry

2022-04-21 00:58 UTC, emisjerry commented on zh-TW.json
> +		"plugin": "外掛程式",
建議用「外掛」。如果原文是用Extension (如Google Chrome和VS Code)用擴充，Plugin 通常大家習慣是用「外掛」，對岸則是用「插件」。

2022-04-21 02:34 UTC, emisjerry commented on zh-TW.json
> +			"label-screenshot-unavailable": "螢幕截圖不可用",
某個主題「尚無螢幕截圖」

2022-04-21 03:34 UTC, emisjerry requested changes
Hi, 感謝你的修改，請參考我的建議。

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"option-indentation-guide": "顯示縮排指示",
用「顯示內縮導引線」?

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"option-indentation-guide-description": "在要點間顯示垂直關聯線，以提供視覺提示。",
「在列表的項目間顯示垂直關聯線，以提供視覺導引。」

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"option-monospace-font-description": "設定程式碼區塊及 frontmatter 等區域的字型。",
「設定程式碼區塊與正文前頁等區域的字型。」 frontmatter前面是翻譯成正文前頁

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"button-donate-to-unlimited": "向 Obsidian Unlimited 贊助",
「贊助 Obsidian Unlimited」

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +		"msg-sandbox-vault": "這是沙盒儲存庫。\n在此儲存庫做出的所有更動不會被儲存。",
「這是沙箱儲存庫。\n對儲存庫的變動皆無法保存。」

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"msg-error-rename-open": "無法重新命名目前已開啟的儲存庫。",
「 開啟中的儲存庫無法重新命名」

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"button-setup": "設置",
建議統一用詞，Setting設定，Setup設置  (國科會 https://terms.naer.edu.tw/search/?q=setup&field=ti&op=AND&group=&num=10)

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"label-sandbox-vault-desc": "探索並試驗各種功能，您的更動不會被儲存。"
「探索並體驗各種功能，請留意你的變動將不會被保存。」

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +		"cycle-list-checklist": "切換要點/核取方塊",
「循環列表/複選框」

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +		"insert-callout": "插入註標",
「插入註標(callout)」建議加註原文

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"option-theme-system": "跟隨系統",
「跟隨作業系統」以明確指明是Windows/macOS/Linux等的系統設定，而不會被誤解是Obsidian

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"option-show-theme-toggle-description": "讓讀者自行切換亮色和暗色主題。",
「讓訪客自行切換明亮或暗黑主題。」明亮或暗黑與外觀裡相同用法

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"option-hide-title-description": "隱藏頁面標題。適用於您已在各個頁面的開頭設置自己的標題的情況。",
"隱藏頁面標題，適用於每個頁面開頭皆有標題的場景。"

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"msg-vault-merge-warning": "如果您連接至遠端資料庫｢{{name}}｣，您本機儲存庫中的筆記將與遠端儲存庫中的筆記合併。若發生衝突，將保存該筆記的最新版本。",
若發生衝突，將留存該筆記的最新版本。

2022-04-21 03:34 UTC, emisjerry commented on zh-TW.json
> +			"name": "檔案復原",
贊成 "還原"

2022-04-23 07:34 UTC, SiderealArt commented on zh-TW.json
> +		"plugin": "外掛程式",
我覺得外掛通常是與遊戲相關的詞，若要指軟體的額外功能，大部分都會講外掛**程式**，如[ Facebook 的介紹](https://developers.facebook.com/docs/plugins?locale=zh_TW)和[卡巴斯基的說明文件](https://support.kaspersky.com/ksc/sp3/zh-Hant/3308.htm)。

2022-04-25 00:50 UTC, emisjerry approved these changes

2022-04-25 00:51 UTC, emisjerry commented
Thanks for your translation.

2022-04-25 00:52 UTC, pan93412 approved these changes
Excellent enough. LGTM.

2022-06-13 16:33 UTC, merged