Update for 0.14.6
obsidianmd/obsidian-translations pull request #616
Opened 2022-04-27 01:39 UTC by 11-check-it-out

2022-05-12 10:11 UTC, kecrily requested changes

2022-05-12 10:11 UTC, kecrily commented on zh.json
> +			"msg-bad-dotfile": "文件名不能以句点开头。",
```suggestion
			"msg-bad-dotfile": "文件名不能以西文句号开头。",
```

2022-05-12 10:11 UTC, kecrily commented on zh.json
> +			"option-site-collaboration": "协作",
```suggestion
			"option-site-collaboration": "站点协作",
```

2022-05-12 10:11 UTC, kecrily commented on zh.json
> +			"option-show-theme-toggle-description": "让读者自行在浅色与深色模式间切换。",
```suggestion
			"option-show-theme-toggle-description": "让访问者自行在明亮与黑暗模式间切换。",
```

2022-05-12 10:11 UTC, kecrily commented on zh.json
> +			"button-get-site": "购买一个。"
```suggestion
			"button-get-site": "购买站点"
```

2022-06-13 16:38 UTC, ericaxu commented
你好，请问这个可以 merge 了吗？

2022-06-13 17:47 UTC, ericaxu commented
我先 merge 了，有什么建议请重新开 PR，谢谢！

2022-06-13 17:47 UTC, merged