translate some words in ja.json
obsidianmd/obsidian-translations pull request #691
Opened 2022-10-15 01:37 UTC by oika

2022-10-20 10:59 UTC, yo-goto requested changes
PRありがとうございます。一箇所だけ気になった部分があったのでそこだけ修正していただけるといいかなと思います🙇‍♂️

2022-10-20 10:59 UTC, yo-goto commented on ja.json
> +		"split-down": "上下分割",
操作的には「右に分割」と「下に分割」なので文字通りの方がいいかなと思います👍

2022-10-20 10:59 UTC, yo-goto commented on ja.json
> +		"split-down": "上下分割",
操作的には「右に分割」と「下に分割」なので文字通りの方がいいかなと思います👍

2022-10-20 14:51 UTC, oika commented
ご指摘の点、修正しましたのでご確認お願いします！

2022-10-20 15:12 UTC, yo-goto approved these changes
良いと思います👍

2022-10-22 03:40 UTC, ericaxu commented
Thank you for your amazing work!

2022-10-22 03:40 UTC, merged