ja: update translation for 0.16.5
obsidianmd/obsidian-translations pull request #698
Opened 2022-10-22 10:50 UTC by yo-goto

2022-10-24 02:46 UTC, taksas requested changes
2か所気になる点がありました。

2022-10-24 02:46 UTC, taksas commented on ja.json
> +			"option-frame-native": "ネイテイブフレーム",
「ネイテイブ」→「ネイティブ」

2022-10-24 02:46 UTC, taksas commented on ja.json
> +			"action-show-in-folder-mac": "ファインダーに表示"
Macでの言い回しはあまり知らないので自信が無いのですが、
「ファインダーに表示」よりも「ファインダーで表示」の方が自然に感じます。どうでしょうか？

2022-10-24 11:22 UTC, yo-goto commented on ja.json
> +			"action-show-in-folder-mac": "ファインダーに表示"
この部分確かに表現的に微妙かもしれません。
当該箇所は一行上の「フォルダに表示」に合わせた記憶がありますが、「エクスプローラでファイルを表示」という表現もあったので、統一できてない感じでしたね。

確かに「~に表示」だとなかったものをあえて表示するみたいなニュアンスで、「で表示」の方が目的に沿った表現かなと思います。調べてみましたが、vscode の翻訳語だと「Finder で表示」ですね。

この系列のものは修正して以下ののように「~で表示」にすべて統一しようと思いますがどうでしょうか?

- フォルダで表示
- ファインダーで表示
- エクスプローラで表示

2022-10-24 11:23 UTC, yo-goto commented on ja.json
> +			"option-frame-native": "ネイテイブフレーム",
修正しておきますね👍

2022-10-24 11:45 UTC, yo-goto commented on ja.json
> +			"action-show-in-folder-mac": "ファインダーに表示"
「に表示」は一つしかなかったのでそのままそこを修正しておきました。

2022-10-24 11:52 UTC, taksas commented on ja.json
> +			"action-show-in-folder-mac": "ファインダーに表示"
変更ありがとうございます。
「〜で表示」統一で良いと思います。

2022-10-24 11:53 UTC, taksas approved these changes

2022-11-01 01:23 UTC, merged

2022-11-01 01:23 UTC, ericaxu commented
Thank you for your work! <3