l10n: zh-TW: update to 0.16.5
obsidianmd/obsidian-translations pull request #707
Opened 2022-10-28 15:27 UTC by 5idereal

2022-10-28 15:28 UTC, 5idereal commented
@pan93412 @emisjerry

2022-10-28 15:38 UTC, pan93412 commented
I'll review it tomorrow.

2022-10-29 08:29 UTC, pan93412 requested changes

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +			"option-native-menus-desc": "整個應用程式的選單將與作業系統相符。並不會受您的主題影響。",
整個應用程式的選單將配合作業系統的風格，不受您的主題影響。

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +		"copied_generic": "已複製到您的剪貼簿",
`已複製到剪貼簿` should be enough.

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +			"link-tab": "與分頁連結...",
Use Unicode punctuation: `…`

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
>  			"option-rename-vault": "重新命名儲存庫……",
Should include only a `…`, as this is an indicator to next operation.

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
>  			"rename-blockid": "重新命名此區塊 ID……",
Should include only a `…`, as this is an indicator to next operation.

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +		"reading-view": "閱讀檢視",
`閱讀顯示模式` ？

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +			"action-create-note-to-the-right": "在右側新增筆記",
`在右側建立筆記`: `新增` is preferred to be the translation of `New`.

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +			"msg-updates-found": "{{count}} 個主題可更新。",
`Found` can be translated as `有`: `有 {{count}} 個主題可更新。`

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +			"msg-installing-theme": "正在安裝主題 \"{{name}}\"……",
The current consensus is `「內容」` instead of `"內容"`. This is discussable.

2022-10-29 08:29 UTC, pan93412 commented on zh-TW.json
> +			"label-leave-vault-confirmation-details-2": "若您希望再次於此儲存庫協作，請聯繫儲存庫的擁有者。",
`聯絡` instead of `聯繫`

2022-10-29 09:15 UTC, pan93412 commented on zh-TW.json
>  			"rename-heading": "重新命名標題……",
I just found another `…` issue. 😢

2022-10-31 01:05 UTC, emisjerry approved these changes

2022-10-31 01:19 UTC, pan93412 approved these changes

2022-11-01 01:20 UTC, merged