update zh-TW.json
obsidianmd/obsidian-translations pull request #740
Opened 2022-12-26 04:01 UTC by 5idereal

2022-12-26 04:02 UTC, 5idereal commented
@pan93412 @emisjerry

2022-12-26 04:36 UTC, pan93412 requested changes

2022-12-26 04:36 UTC, pan93412 commented on zh-TW.json
> +			"label-donate-modal-text1": "外掛程式的開發者為社群的志願者，出於熱情而達成令人嘆服的事情，如果您覺得此外掛程式很好用，請考慮贊助其開發。",
這一句不太通順

2022-12-26 04:36 UTC, pan93412 commented on zh-TW.json
> +			"label-donate-modal-text2": "您的贊助將全數給予外掛程式的開發者；Obsidian 不會從中抽成。它們選擇的贊助平台可能會收取手續費。",
標點符號使用上有點問題，然後開發者是人，不應該使用「它」。

    您的贊助將全數給予外掛程式的開發者，Obsidian 不會從中抽成。開發者選擇的贊助平台可能會收取手續費。

2022-12-26 04:36 UTC, pan93412 commented on zh-TW.json
> +		"label-existing-backlink_plural": "目前有 {{links}} 指向此筆記。",
這個 {{links}} 應該是數字，需要加上量詞（目前有 {{links}} 個指向此筆記）

2022-12-26 04:36 UTC, pan93412 commented on zh-TW.json
> +		"new-window": "新視窗",
建立視窗？

2022-12-26 04:36 UTC, pan93412 commented on zh-TW.json
> +			"action-convert-to-file": "轉換成檔案……",
表示下一層的選單項目只需要三個點。

2022-12-26 04:36 UTC, pan93412 commented on zh-TW.json
> +			"action-narrow": "縮小至區塊……",
Action 類應該都是說下一層，用三個點會比較好。L1690,L1691 也是同個問題。

2022-12-26 05:35 UTC, emisjerry approved these changes
辛苦了。

2022-12-27 08:36 UTC, 5idereal commented on zh-TW.json
> +			"label-donate-modal-text1": "外掛程式的開發者為社群的志願者，出於熱情而達成令人嘆服的事情，如果您覺得此外掛程式很好用，請考慮贊助其開發。",
改為 `此外掛程式由社群的志願者出於熱情而開發，如果您覺得好用，請考慮贊助。`?

2022-12-27 09:12 UTC, emisjerry approved these changes

2022-12-27 09:51 UTC, pan93412 approved these changes

2022-12-27 09:51 UTC, pan93412 commented
辛苦了～💯💯

2023-01-03 18:18 UTC, merged

2023-01-03 18:18 UTC, ericaxu commented
Thank you for your work! <3