Translate strings for de.json
obsidianmd/obsidian-translations pull request #794
Opened 2023-05-15 09:32 UTC by FloriF

2023-05-16 12:57 UTC, joethei requested changes

2023-05-16 12:57 UTC, joethei commented on de.json
> +			"option-customize-navigation-desc": "Überschreibt die Reihenfolge der Navigationselemente und versteckt Seiten oder Ordner.",
"Überschreibe" würde hier besser passen.

2023-05-16 12:57 UTC, joethei commented on de.json
> +			"option-hide-items-in-navigation-desc": "Rechtsklick und wähle \"Verstecken\", um bestimmte Seiten von der Navigation auszuschließen. Die Seiten sind immernoch über Links oder die direkte URL erre
"Die Seiten werde weiterhin über Links oder die direkte URL erreichbar sein."

2023-05-18 11:35 UTC, FloriF commented on de.json
> +			"label-show-user-assigned": "Zugewiesen von Dir",
Mein Gedanke war: Bisher gibt es keine Stelle, an der in Obsidian von "mein" gesprochen wird, es ist immer "Dein" - der Konsistenz halber würde das so also nicht mehr Sinn machen?

2023-07-06 19:54 UTC, ericaxu commented
@FloriF Hi! Did you get a chance to review @joethei 's suggestions?

2023-07-11 08:24 UTC, FloriF commented
@ericaxu I changed almost all suggestions from the review now. Still not sure if I handled and used the review function correctly, though^^'

@joethei Skipped one suggested change for consistency reasons: 'Überschreibe' vs 'Überschreibt' - we use the second version almost everywhere, e.g., 'Zeigt ... an', 'Korrigiert' etc.

2023-07-14 07:37 UTC, joethei approved these changes

2023-07-14 07:37 UTC, merged